api_platform:
    title: 'Bilemo API'
    description: 'Projet n°7 - OpenClassRooms'
    version: '1.0.0'
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]

    patch_formats:
        json: [ 'application/merge-patch+json' ]

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    defaults:
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        pagination_items_per_page: 10